/* tslint:disable */
/* eslint-disable */
/**
 * Corbado Frontend API
 * Overview of all Corbado Frontend API calls to implement passwordless authentication.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@corbado.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface AuthenticationResponse
 */
export interface AuthenticationResponse {
    /**
     * Only given when project environment is dev
     * @type {string}
     * @memberof AuthenticationResponse
     */
    'longSession'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationResponse
     */
    'shortSession': string;
}
/**
 * 
 * @export
 * @interface BlockBody
 */
export interface BlockBody {
    /**
     * 
     * @type {BlockType}
     * @memberof BlockBody
     */
    'block': BlockType;
    /**
     * 
     * @type {BlockBodyData}
     * @memberof BlockBody
     */
    'data': BlockBodyData;
    /**
     * 
     * @type {Array<BlockBody>}
     * @memberof BlockBody
     */
    'alternatives'?: Array<BlockBody>;
    /**
     * 
     * @type {RequestError}
     * @memberof BlockBody
     */
    'error'?: RequestError;
}


/**
 * 
 * @export
 * @interface BlockBodyData
 */
export interface BlockBodyData {
    /**
     * 
     * @type {string}
     * @memberof BlockBodyData
     */
    'challenge': string;
    /**
     * 
     * @type {string}
     * @memberof BlockBodyData
     */
    'userHandle': string;
    /**
     * 
     * @type {VerificationMethod}
     * @memberof BlockBodyData
     */
    'verificationMethod': VerificationMethod;
    /**
     * 
     * @type {string}
     * @memberof BlockBodyData
     */
    'identifier': string;
    /**
     * 
     * @type {number}
     * @memberof BlockBodyData
     */
    'retryNotBefore'?: number;
    /**
     * 
     * @type {RequestError}
     * @memberof BlockBodyData
     */
    'error'?: RequestError;
    /**
     * 
     * @type {Array<object>}
     * @memberof BlockBodyData
     */
    'alternativeVerificationMethods': Array<object>;
    /**
     * Only given when project environment is dev
     * @type {string}
     * @memberof BlockBodyData
     */
    'longSession'?: string;
    /**
     * 
     * @type {string}
     * @memberof BlockBodyData
     */
    'shortSession': string;
    /**
     * 
     * @type {Array<LoginIdentifierWithError>}
     * @memberof BlockBodyData
     */
    'identifiers': Array<LoginIdentifierWithError>;
    /**
     * 
     * @type {GeneralBlockSignupInitFullName}
     * @memberof BlockBodyData
     */
    'fullName'?: GeneralBlockSignupInitFullName;
    /**
     * 
     * @type {LoginIdentifierType}
     * @memberof BlockBodyData
     */
    'type': LoginIdentifierType;
}


/**
 * 
 * @export
 * @enum {string}
 */

export const BlockType = {
    SignupInit: 'signup-init',
    PasskeyAppend: 'passkey-append',
    PhoneVerify: 'phone-verify',
    EmailVerify: 'email-verify',
    PasskeyAppended: 'passkey-appended',
    Completed: 'completed',
    SocialVerify: 'social-verify',
    UsernameCollect: 'username-collect',
    PhoneCollect: 'phone-collect'
} as const;

export type BlockType = typeof BlockType[keyof typeof BlockType];


/**
 * 
 * @export
 * @interface EmailVerifyFinishReq
 */
export interface EmailVerifyFinishReq {
    /**
     * 
     * @type {object}
     * @memberof EmailVerifyFinishReq
     */
    'clientInfo': object;
    /**
     * 
     * @type {string}
     * @memberof EmailVerifyFinishReq
     */
    'code': string;
    /**
     * 
     * @type {VerificationMethod}
     * @memberof EmailVerifyFinishReq
     */
    'verificationType': VerificationMethod;
}


/**
 * tbd.
 * @export
 * @interface EmailVerifyStartReq
 */
export interface EmailVerifyStartReq {
    /**
     * 
     * @type {VerificationMethod}
     * @memberof EmailVerifyStartReq
     */
    'verificationType': VerificationMethod;
}


/**
 * 
 * @export
 * @interface GeneralBlockPasskeyAppend
 */
export interface GeneralBlockPasskeyAppend {
    /**
     * 
     * @type {string}
     * @memberof GeneralBlockPasskeyAppend
     */
    'challenge': string;
    /**
     * 
     * @type {string}
     * @memberof GeneralBlockPasskeyAppend
     */
    'userHandle': string;
}
/**
 * 
 * @export
 * @interface GeneralBlockSignupInit
 */
export interface GeneralBlockSignupInit {
    /**
     * 
     * @type {Array<LoginIdentifierWithError>}
     * @memberof GeneralBlockSignupInit
     */
    'identifiers': Array<LoginIdentifierWithError>;
    /**
     * 
     * @type {GeneralBlockSignupInitFullName}
     * @memberof GeneralBlockSignupInit
     */
    'fullName'?: GeneralBlockSignupInitFullName;
}
/**
 * 
 * @export
 * @interface GeneralBlockSignupInitFullName
 */
export interface GeneralBlockSignupInitFullName {
    /**
     * 
     * @type {string}
     * @memberof GeneralBlockSignupInitFullName
     */
    'value': string;
    /**
     * 
     * @type {RequestError}
     * @memberof GeneralBlockSignupInitFullName
     */
    'error'?: RequestError;
}
/**
 * 
 * @export
 * @interface GeneralBlockVerifyIdentifier
 */
export interface GeneralBlockVerifyIdentifier {
    /**
     * 
     * @type {VerificationMethod}
     * @memberof GeneralBlockVerifyIdentifier
     */
    'verificationMethod': VerificationMethod;
    /**
     * 
     * @type {string}
     * @memberof GeneralBlockVerifyIdentifier
     */
    'identifier': string;
    /**
     * 
     * @type {number}
     * @memberof GeneralBlockVerifyIdentifier
     */
    'retryNotBefore'?: number;
    /**
     * 
     * @type {RequestError}
     * @memberof GeneralBlockVerifyIdentifier
     */
    'error'?: RequestError;
    /**
     * 
     * @type {Array<object>}
     * @memberof GeneralBlockVerifyIdentifier
     */
    'alternativeVerificationMethods': Array<object>;
}


/**
 * 
 * @export
 * @interface LoginIdentifier
 */
export interface LoginIdentifier {
    /**
     * 
     * @type {LoginIdentifierType}
     * @memberof LoginIdentifier
     */
    'type': LoginIdentifierType;
    /**
     * 
     * @type {string}
     * @memberof LoginIdentifier
     */
    'identifier': string;
}


/**
 * 
 * @export
 * @interface LoginIdentifierConfig
 */
export interface LoginIdentifierConfig {
    /**
     * 
     * @type {LoginIdentifierType}
     * @memberof LoginIdentifierConfig
     */
    'type': LoginIdentifierType;
    /**
     * 
     * @type {string}
     * @memberof LoginIdentifierConfig
     */
    'enforceVerification': LoginIdentifierConfigEnforceVerificationEnum;
    /**
     * 
     * @type {boolean}
     * @memberof LoginIdentifierConfig
     */
    'useAsLoginIdentifier': boolean;
    /**
     * 
     * @type {object}
     * @memberof LoginIdentifierConfig
     */
    'metadata'?: object;
}

export const LoginIdentifierConfigEnforceVerificationEnum = {
    None: 'none',
    Signup: 'signup',
    BeforePasskeyLogin: 'before-passkey-login'
} as const;

export type LoginIdentifierConfigEnforceVerificationEnum = typeof LoginIdentifierConfigEnforceVerificationEnum[keyof typeof LoginIdentifierConfigEnforceVerificationEnum];

/**
 * 
 * @export
 * @enum {string}
 */

export const LoginIdentifierType = {
    Email: 'email',
    Phone: 'phone',
    Username: 'username'
} as const;

export type LoginIdentifierType = typeof LoginIdentifierType[keyof typeof LoginIdentifierType];


/**
 * 
 * @export
 * @interface LoginIdentifierWithError
 */
export interface LoginIdentifierWithError {
    /**
     * 
     * @type {LoginIdentifierType}
     * @memberof LoginIdentifierWithError
     */
    'type': LoginIdentifierType;
    /**
     * 
     * @type {string}
     * @memberof LoginIdentifierWithError
     */
    'identifier': string;
    /**
     * 
     * @type {RequestError}
     * @memberof LoginIdentifierWithError
     */
    'error'?: RequestError;
}


/**
 * 
 * @export
 * @interface MePasskeyAppendStartRsp
 */
export interface MePasskeyAppendStartRsp {
    /**
     * 
     * @type {string}
     * @memberof MePasskeyAppendStartRsp
     */
    'challenge': string;
}
/**
 * 
 * @export
 * @interface MePasskeyDeleteRsp
 */
export interface MePasskeyDeleteRsp {
    /**
     * 
     * @type {string}
     * @memberof MePasskeyDeleteRsp
     */
    'id': string;
}
/**
 * 
 * @export
 * @interface MePasskeyRsp
 */
export interface MePasskeyRsp {
    /**
     * 
     * @type {Array<PassKeyItem>}
     * @memberof MePasskeyRsp
     */
    'passkeys': Array<PassKeyItem>;
    /**
     * 
     * @type {Paging}
     * @memberof MePasskeyRsp
     */
    'paging'?: Paging;
}
/**
 * 
 * @export
 * @interface Paging
 */
export interface Paging {
    /**
     * current page returned in response
     * @type {number}
     * @memberof Paging
     */
    'page': number;
    /**
     * total number of pages available
     * @type {number}
     * @memberof Paging
     */
    'totalPages': number;
    /**
     * total number of items available
     * @type {number}
     * @memberof Paging
     */
    'totalItems': number;
}
/**
 * 
 * @export
 * @interface PassKeyItem
 */
export interface PassKeyItem {
    /**
     * 
     * @type {string}
     * @memberof PassKeyItem
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof PassKeyItem
     */
    'credentialHash': string;
    /**
     * 
     * @type {string}
     * @memberof PassKeyItem
     */
    'aaguid': string;
    /**
     * 
     * @type {string}
     * @memberof PassKeyItem
     */
    'userAgent': string;
    /**
     * 
     * @type {string}
     * @memberof PassKeyItem
     */
    'attestationType': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PassKeyItem
     */
    'transport': Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof PassKeyItem
     */
    'backupEligible': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PassKeyItem
     */
    'backupState': boolean;
    /**
     * Timestamp of when the entity was last used in yyyy-MM-dd\'T\'HH:mm:ss format
     * @type {string}
     * @memberof PassKeyItem
     */
    'lastUsed': string;
    /**
     * Status
     * @type {string}
     * @memberof PassKeyItem
     */
    'status': PassKeyItemStatusEnum;
    /**
     * Timestamp of when the entity was created in yyyy-MM-dd\'T\'HH:mm:ss format
     * @type {string}
     * @memberof PassKeyItem
     */
    'created': string;
}

export const PassKeyItemStatusEnum = {
    Pending: 'pending',
    Active: 'active'
} as const;

export type PassKeyItemStatusEnum = typeof PassKeyItemStatusEnum[keyof typeof PassKeyItemStatusEnum];

/**
 * tbd.
 * @export
 * @interface PasskeyAppendFinishReq
 */
export interface PasskeyAppendFinishReq {
    /**
     * 
     * @type {object}
     * @memberof PasskeyAppendFinishReq
     */
    'clientInfo': object;
    /**
     * 
     * @type {string}
     * @memberof PasskeyAppendFinishReq
     */
    'signedChallenge': string;
}
/**
 * tbd.
 * @export
 * @interface PasskeyAppendStartReq
 */
export interface PasskeyAppendStartReq {
    /**
     * 
     * @type {object}
     * @memberof PasskeyAppendStartReq
     */
    'clientInfo': object;
}
/**
 * 
 * @export
 * @interface PhoneCollectReq
 */
export interface PhoneCollectReq {
    /**
     * 
     * @type {object}
     * @memberof PhoneCollectReq
     */
    'clientInfo': object;
    /**
     * 
     * @type {string}
     * @memberof PhoneCollectReq
     */
    'value': string;
}
/**
 * 
 * @export
 * @interface PhoneVerifyFinishReq
 */
export interface PhoneVerifyFinishReq {
    /**
     * 
     * @type {object}
     * @memberof PhoneVerifyFinishReq
     */
    'clientInfo': object;
    /**
     * 
     * @type {string}
     * @memberof PhoneVerifyFinishReq
     */
    'code': string;
}
/**
 * tbd.
 * @export
 * @interface PhoneVerifyStartReq
 */
export interface PhoneVerifyStartReq {
    /**
     * 
     * @type {object}
     * @memberof PhoneVerifyStartReq
     */
    'clientInfo': object;
}
/**
 * tbd.
 * @export
 * @interface ProcessInitReq
 */
export interface ProcessInitReq {
    /**
     * 
     * @type {object}
     * @memberof ProcessInitReq
     */
    'clientInfo': object;
}
/**
 * tbd.
 * @export
 * @interface ProcessInitRsp
 */
export interface ProcessInitRsp {
    /**
     * 
     * @type {string}
     * @memberof ProcessInitRsp
     */
    'token': string;
    /**
     * 
     * @type {number}
     * @memberof ProcessInitRsp
     */
    'expiresAt': number;
    /**
     * 
     * @type {BlockBody}
     * @memberof ProcessInitRsp
     */
    'initialBlock': BlockBody;
}
/**
 * 
 * @export
 * @interface RequestError
 */
export interface RequestError {
    /**
     * 
     * @type {string}
     * @memberof RequestError
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof RequestError
     */
    'message': string;
}
/**
 * tbd.
 * @export
 * @interface SignupInitReq
 */
export interface SignupInitReq {
    /**
     * 
     * @type {string}
     * @memberof SignupInitReq
     */
    'fullName'?: string;
    /**
     * 
     * @type {Array<LoginIdentifier>}
     * @memberof SignupInitReq
     */
    'identifiers': Array<LoginIdentifier>;
}
/**
 * 
 * @export
 * @interface SignupInitRsp
 */
export interface SignupInitRsp {
    /**
     * 
     * @type {BlockType}
     * @memberof SignupInitRsp
     */
    'block': BlockType;
    /**
     * 
     * @type {BlockBodyData}
     * @memberof SignupInitRsp
     */
    'data': BlockBodyData;
    /**
     * 
     * @type {Array<BlockBody>}
     * @memberof SignupInitRsp
     */
    'alternatives'?: Array<BlockBody>;
    /**
     * 
     * @type {RequestError}
     * @memberof SignupInitRsp
     */
    'error'?: RequestError;
}


/**
 * 
 * @export
 * @interface SocialVerifyStartReq
 */
export interface SocialVerifyStartReq {
    /**
     * 
     * @type {object}
     * @memberof SocialVerifyStartReq
     */
    'clientInfo': object;
}
/**
 * tbd.
 * @export
 * @interface UpdateComponentConfigReq
 */
export interface UpdateComponentConfigReq {
    /**
     * 
     * @type {Array<LoginIdentifierConfig>}
     * @memberof UpdateComponentConfigReq
     */
    'identifiers': Array<LoginIdentifierConfig>;
}
/**
 * 
 * @export
 * @interface UpdateComponentConfigRsp
 */
export interface UpdateComponentConfigRsp {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateComponentConfigRsp
     */
    'success'?: boolean;
}
/**
 * 
 * @export
 * @interface UsernameCollectReq
 */
export interface UsernameCollectReq {
    /**
     * 
     * @type {object}
     * @memberof UsernameCollectReq
     */
    'clientInfo': object;
    /**
     * 
     * @type {string}
     * @memberof UsernameCollectReq
     */
    'value': string;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const VerificationMethod = {
    EmailLink: 'email-link',
    EmailOtp: 'email-otp',
    SmsOtp: 'sms-otp'
} as const;

export type VerificationMethod = typeof VerificationMethod[keyof typeof VerificationMethod];


/**
 * 
 * @export
 * @interface VerifyIdentifierRsp
 */
export interface VerifyIdentifierRsp {
    /**
     * 
     * @type {object}
     * @memberof VerifyIdentifierRsp
     */
    'primary': object;
    /**
     * 
     * @type {object}
     * @memberof VerifyIdentifierRsp
     */
    'alternatives': object;
}
/**
 * 
 * @export
 * @interface VerifyPasskeyRsp
 */
export interface VerifyPasskeyRsp {
    /**
     * 
     * @type {object}
     * @memberof VerifyPasskeyRsp
     */
    'primary': object;
    /**
     * 
     * @type {object}
     * @memberof VerifyPasskeyRsp
     */
    'alternatives': object;
}

/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * tbd
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blockSkip: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/auth/block/skip`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * tbd
         * @param {EmailVerifyFinishReq} emailVerifyFinishReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        emailVerifyFinish: async (emailVerifyFinishReq: EmailVerifyFinishReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'emailVerifyFinishReq' is not null or undefined
            assertParamExists('emailVerifyFinish', 'emailVerifyFinishReq', emailVerifyFinishReq)
            const localVarPath = `/v2/auth/email/verify/finish`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(emailVerifyFinishReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * tbd
         * @param {EmailVerifyStartReq} emailVerifyStartReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        emailVerifyStart: async (emailVerifyStartReq: EmailVerifyStartReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'emailVerifyStartReq' is not null or undefined
            assertParamExists('emailVerifyStart', 'emailVerifyStartReq', emailVerifyStartReq)
            const localVarPath = `/v2/auth/email/verify/start`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(emailVerifyStartReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * tbd
         * @param {PasskeyAppendFinishReq} passkeyAppendFinishReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        passkeyAppendFinish: async (passkeyAppendFinishReq: PasskeyAppendFinishReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'passkeyAppendFinishReq' is not null or undefined
            assertParamExists('passkeyAppendFinish', 'passkeyAppendFinishReq', passkeyAppendFinishReq)
            const localVarPath = `/v2/auth/passkey/append/finish`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(passkeyAppendFinishReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * tbd
         * @param {PasskeyAppendStartReq} passkeyAppendStartReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        passkeyAppendStart: async (passkeyAppendStartReq: PasskeyAppendStartReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'passkeyAppendStartReq' is not null or undefined
            assertParamExists('passkeyAppendStart', 'passkeyAppendStartReq', passkeyAppendStartReq)
            const localVarPath = `/v2/auth/passkey/append/start`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(passkeyAppendStartReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * tbd
         * @param {PhoneCollectReq} phoneCollectReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        phoneCollect: async (phoneCollectReq: PhoneCollectReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'phoneCollectReq' is not null or undefined
            assertParamExists('phoneCollect', 'phoneCollectReq', phoneCollectReq)
            const localVarPath = `/v2/auth/phone/collect`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(phoneCollectReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * tbd
         * @param {PhoneVerifyFinishReq} phoneVerifyFinishReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        phoneVerifyFinish: async (phoneVerifyFinishReq: PhoneVerifyFinishReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'phoneVerifyFinishReq' is not null or undefined
            assertParamExists('phoneVerifyFinish', 'phoneVerifyFinishReq', phoneVerifyFinishReq)
            const localVarPath = `/v2/auth/phone/verify/finish`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(phoneVerifyFinishReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * tbd
         * @param {PhoneVerifyStartReq} phoneVerifyStartReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        phoneVerifyStart: async (phoneVerifyStartReq: PhoneVerifyStartReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'phoneVerifyStartReq' is not null or undefined
            assertParamExists('phoneVerifyStart', 'phoneVerifyStartReq', phoneVerifyStartReq)
            const localVarPath = `/v2/auth/phone/verify/start`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(phoneVerifyStartReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * tbd
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        processComplete: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/auth/process/complete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * tbd
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        processGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/auth/process`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * tbd
         * @param {ProcessInitReq} processInitReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        processInit: async (processInitReq: ProcessInitReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'processInitReq' is not null or undefined
            assertParamExists('processInit', 'processInitReq', processInitReq)
            const localVarPath = `/v2/auth/process/init`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(processInitReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * tbd
         * @param {SignupInitReq} signupInitReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signupInit: async (signupInitReq: SignupInitReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signupInitReq' is not null or undefined
            assertParamExists('signupInit', 'signupInitReq', signupInitReq)
            const localVarPath = `/v2/auth/signup/init`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signupInitReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * tbd
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        socialVerifyFinish: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/auth/social/verify/finish`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * tbd
         * @param {SocialVerifyStartReq} socialVerifyStartReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        socialVerifyStart: async (socialVerifyStartReq: SocialVerifyStartReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'socialVerifyStartReq' is not null or undefined
            assertParamExists('socialVerifyStart', 'socialVerifyStartReq', socialVerifyStartReq)
            const localVarPath = `/v2/auth/social/verify/start`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(socialVerifyStartReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * tbd
         * @param {UsernameCollectReq} usernameCollectReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usernameCollect: async (usernameCollectReq: UsernameCollectReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'usernameCollectReq' is not null or undefined
            assertParamExists('usernameCollect', 'usernameCollectReq', usernameCollectReq)
            const localVarPath = `/v2/auth/username/collect`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(usernameCollectReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * tbd
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async blockSkip(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BlockBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.blockSkip(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * tbd
         * @param {EmailVerifyFinishReq} emailVerifyFinishReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async emailVerifyFinish(emailVerifyFinishReq: EmailVerifyFinishReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BlockBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.emailVerifyFinish(emailVerifyFinishReq, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * tbd
         * @param {EmailVerifyStartReq} emailVerifyStartReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async emailVerifyStart(emailVerifyStartReq: EmailVerifyStartReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BlockBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.emailVerifyStart(emailVerifyStartReq, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * tbd
         * @param {PasskeyAppendFinishReq} passkeyAppendFinishReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async passkeyAppendFinish(passkeyAppendFinishReq: PasskeyAppendFinishReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BlockBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.passkeyAppendFinish(passkeyAppendFinishReq, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * tbd
         * @param {PasskeyAppendStartReq} passkeyAppendStartReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async passkeyAppendStart(passkeyAppendStartReq: PasskeyAppendStartReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BlockBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.passkeyAppendStart(passkeyAppendStartReq, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * tbd
         * @param {PhoneCollectReq} phoneCollectReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async phoneCollect(phoneCollectReq: PhoneCollectReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BlockBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.phoneCollect(phoneCollectReq, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * tbd
         * @param {PhoneVerifyFinishReq} phoneVerifyFinishReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async phoneVerifyFinish(phoneVerifyFinishReq: PhoneVerifyFinishReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BlockBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.phoneVerifyFinish(phoneVerifyFinishReq, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * tbd
         * @param {PhoneVerifyStartReq} phoneVerifyStartReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async phoneVerifyStart(phoneVerifyStartReq: PhoneVerifyStartReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BlockBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.phoneVerifyStart(phoneVerifyStartReq, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * tbd
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async processComplete(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BlockBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.processComplete(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * tbd
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async processGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BlockBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.processGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * tbd
         * @param {ProcessInitReq} processInitReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async processInit(processInitReq: ProcessInitReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProcessInitRsp>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.processInit(processInitReq, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * tbd
         * @param {SignupInitReq} signupInitReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signupInit(signupInitReq: SignupInitReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignupInitRsp>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signupInit(signupInitReq, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * tbd
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async socialVerifyFinish(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BlockBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.socialVerifyFinish(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * tbd
         * @param {SocialVerifyStartReq} socialVerifyStartReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async socialVerifyStart(socialVerifyStartReq: SocialVerifyStartReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BlockBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.socialVerifyStart(socialVerifyStartReq, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * tbd
         * @param {UsernameCollectReq} usernameCollectReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usernameCollect(usernameCollectReq: UsernameCollectReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BlockBody>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usernameCollect(usernameCollectReq, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * tbd
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        blockSkip(options?: any): AxiosPromise<BlockBody> {
            return localVarFp.blockSkip(options).then((request) => request(axios, basePath));
        },
        /**
         * tbd
         * @param {EmailVerifyFinishReq} emailVerifyFinishReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        emailVerifyFinish(emailVerifyFinishReq: EmailVerifyFinishReq, options?: any): AxiosPromise<BlockBody> {
            return localVarFp.emailVerifyFinish(emailVerifyFinishReq, options).then((request) => request(axios, basePath));
        },
        /**
         * tbd
         * @param {EmailVerifyStartReq} emailVerifyStartReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        emailVerifyStart(emailVerifyStartReq: EmailVerifyStartReq, options?: any): AxiosPromise<BlockBody> {
            return localVarFp.emailVerifyStart(emailVerifyStartReq, options).then((request) => request(axios, basePath));
        },
        /**
         * tbd
         * @param {PasskeyAppendFinishReq} passkeyAppendFinishReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        passkeyAppendFinish(passkeyAppendFinishReq: PasskeyAppendFinishReq, options?: any): AxiosPromise<BlockBody> {
            return localVarFp.passkeyAppendFinish(passkeyAppendFinishReq, options).then((request) => request(axios, basePath));
        },
        /**
         * tbd
         * @param {PasskeyAppendStartReq} passkeyAppendStartReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        passkeyAppendStart(passkeyAppendStartReq: PasskeyAppendStartReq, options?: any): AxiosPromise<BlockBody> {
            return localVarFp.passkeyAppendStart(passkeyAppendStartReq, options).then((request) => request(axios, basePath));
        },
        /**
         * tbd
         * @param {PhoneCollectReq} phoneCollectReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        phoneCollect(phoneCollectReq: PhoneCollectReq, options?: any): AxiosPromise<BlockBody> {
            return localVarFp.phoneCollect(phoneCollectReq, options).then((request) => request(axios, basePath));
        },
        /**
         * tbd
         * @param {PhoneVerifyFinishReq} phoneVerifyFinishReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        phoneVerifyFinish(phoneVerifyFinishReq: PhoneVerifyFinishReq, options?: any): AxiosPromise<BlockBody> {
            return localVarFp.phoneVerifyFinish(phoneVerifyFinishReq, options).then((request) => request(axios, basePath));
        },
        /**
         * tbd
         * @param {PhoneVerifyStartReq} phoneVerifyStartReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        phoneVerifyStart(phoneVerifyStartReq: PhoneVerifyStartReq, options?: any): AxiosPromise<BlockBody> {
            return localVarFp.phoneVerifyStart(phoneVerifyStartReq, options).then((request) => request(axios, basePath));
        },
        /**
         * tbd
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        processComplete(options?: any): AxiosPromise<BlockBody> {
            return localVarFp.processComplete(options).then((request) => request(axios, basePath));
        },
        /**
         * tbd
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        processGet(options?: any): AxiosPromise<BlockBody> {
            return localVarFp.processGet(options).then((request) => request(axios, basePath));
        },
        /**
         * tbd
         * @param {ProcessInitReq} processInitReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        processInit(processInitReq: ProcessInitReq, options?: any): AxiosPromise<ProcessInitRsp> {
            return localVarFp.processInit(processInitReq, options).then((request) => request(axios, basePath));
        },
        /**
         * tbd
         * @param {SignupInitReq} signupInitReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signupInit(signupInitReq: SignupInitReq, options?: any): AxiosPromise<SignupInitRsp> {
            return localVarFp.signupInit(signupInitReq, options).then((request) => request(axios, basePath));
        },
        /**
         * tbd
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        socialVerifyFinish(options?: any): AxiosPromise<BlockBody> {
            return localVarFp.socialVerifyFinish(options).then((request) => request(axios, basePath));
        },
        /**
         * tbd
         * @param {SocialVerifyStartReq} socialVerifyStartReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        socialVerifyStart(socialVerifyStartReq: SocialVerifyStartReq, options?: any): AxiosPromise<BlockBody> {
            return localVarFp.socialVerifyStart(socialVerifyStartReq, options).then((request) => request(axios, basePath));
        },
        /**
         * tbd
         * @param {UsernameCollectReq} usernameCollectReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usernameCollect(usernameCollectReq: UsernameCollectReq, options?: any): AxiosPromise<BlockBody> {
            return localVarFp.usernameCollect(usernameCollectReq, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * tbd
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public blockSkip(options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).blockSkip(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * tbd
     * @param {EmailVerifyFinishReq} emailVerifyFinishReq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public emailVerifyFinish(emailVerifyFinishReq: EmailVerifyFinishReq, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).emailVerifyFinish(emailVerifyFinishReq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * tbd
     * @param {EmailVerifyStartReq} emailVerifyStartReq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public emailVerifyStart(emailVerifyStartReq: EmailVerifyStartReq, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).emailVerifyStart(emailVerifyStartReq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * tbd
     * @param {PasskeyAppendFinishReq} passkeyAppendFinishReq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public passkeyAppendFinish(passkeyAppendFinishReq: PasskeyAppendFinishReq, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).passkeyAppendFinish(passkeyAppendFinishReq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * tbd
     * @param {PasskeyAppendStartReq} passkeyAppendStartReq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public passkeyAppendStart(passkeyAppendStartReq: PasskeyAppendStartReq, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).passkeyAppendStart(passkeyAppendStartReq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * tbd
     * @param {PhoneCollectReq} phoneCollectReq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public phoneCollect(phoneCollectReq: PhoneCollectReq, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).phoneCollect(phoneCollectReq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * tbd
     * @param {PhoneVerifyFinishReq} phoneVerifyFinishReq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public phoneVerifyFinish(phoneVerifyFinishReq: PhoneVerifyFinishReq, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).phoneVerifyFinish(phoneVerifyFinishReq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * tbd
     * @param {PhoneVerifyStartReq} phoneVerifyStartReq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public phoneVerifyStart(phoneVerifyStartReq: PhoneVerifyStartReq, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).phoneVerifyStart(phoneVerifyStartReq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * tbd
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public processComplete(options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).processComplete(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * tbd
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public processGet(options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).processGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * tbd
     * @param {ProcessInitReq} processInitReq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public processInit(processInitReq: ProcessInitReq, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).processInit(processInitReq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * tbd
     * @param {SignupInitReq} signupInitReq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public signupInit(signupInitReq: SignupInitReq, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).signupInit(signupInitReq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * tbd
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public socialVerifyFinish(options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).socialVerifyFinish(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * tbd
     * @param {SocialVerifyStartReq} socialVerifyStartReq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public socialVerifyStart(socialVerifyStartReq: SocialVerifyStartReq, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).socialVerifyStart(socialVerifyStartReq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * tbd
     * @param {UsernameCollectReq} usernameCollectReq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public usernameCollect(usernameCollectReq: UsernameCollectReq, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).usernameCollect(usernameCollectReq, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * tbd
         * @param {UpdateComponentConfigReq} updateComponentConfigReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateComponentConfig: async (updateComponentConfigReq: UpdateComponentConfigReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateComponentConfigReq' is not null or undefined
            assertParamExists('updateComponentConfig', 'updateComponentConfigReq', updateComponentConfigReq)
            const localVarPath = `/v2/component-config`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateComponentConfigReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * tbd
         * @param {UpdateComponentConfigReq} updateComponentConfigReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateComponentConfig(updateComponentConfigReq: UpdateComponentConfigReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateComponentConfigRsp>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateComponentConfig(updateComponentConfigReq, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * tbd
         * @param {UpdateComponentConfigReq} updateComponentConfigReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateComponentConfig(updateComponentConfigReq: UpdateComponentConfigReq, options?: any): AxiosPromise<UpdateComponentConfigRsp> {
            return localVarFp.updateComponentConfig(updateComponentConfigReq, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * tbd
     * @param {UpdateComponentConfigReq} updateComponentConfigReq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateComponentConfig(updateComponentConfigReq: UpdateComponentConfigReq, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateComponentConfig(updateComponentConfigReq, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Finish passkey append
         * @param {PasskeyAppendFinishReq} passkeyAppendFinishReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        currentUserPasskeyAppendFinish: async (passkeyAppendFinishReq: PasskeyAppendFinishReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'passkeyAppendFinishReq' is not null or undefined
            assertParamExists('currentUserPasskeyAppendFinish', 'passkeyAppendFinishReq', passkeyAppendFinishReq)
            const localVarPath = `/v2/me/passkeys/append/finish`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(passkeyAppendFinishReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Start passkey append
         * @param {PasskeyAppendStartReq} passkeyAppendStartReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        currentUserPasskeyAppendStart: async (passkeyAppendStartReq: PasskeyAppendStartReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'passkeyAppendStartReq' is not null or undefined
            assertParamExists('currentUserPasskeyAppendStart', 'passkeyAppendStartReq', passkeyAppendStartReq)
            const localVarPath = `/v2/me/passkeys/append/start`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(passkeyAppendStartReq, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete current user\'s passkeys
         * @param {string} credentialID Credential ID from passkeys
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        currentUserPasskeyDelete: async (credentialID: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'credentialID' is not null or undefined
            assertParamExists('currentUserPasskeyDelete', 'credentialID', credentialID)
            const localVarPath = `/v2/me/passkeys/{credentialID}`
                .replace(`{${"credentialID"}}`, encodeURIComponent(String(credentialID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets current user\'s passkeys
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        currentUserPasskeyGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/me/passkeys`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Performs session logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        currentUserSessionLogout: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/me/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Performs session refresh
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        currentUserSessionRefresh: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/me/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication projectID required
            await setApiKeyToObject(localVarHeaderParameter, "X-Corbado-ProjectID", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * Finish passkey append
         * @param {PasskeyAppendFinishReq} passkeyAppendFinishReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async currentUserPasskeyAppendFinish(passkeyAppendFinishReq: PasskeyAppendFinishReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.currentUserPasskeyAppendFinish(passkeyAppendFinishReq, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Start passkey append
         * @param {PasskeyAppendStartReq} passkeyAppendStartReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async currentUserPasskeyAppendStart(passkeyAppendStartReq: PasskeyAppendStartReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MePasskeyAppendStartRsp>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.currentUserPasskeyAppendStart(passkeyAppendStartReq, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Delete current user\'s passkeys
         * @param {string} credentialID Credential ID from passkeys
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async currentUserPasskeyDelete(credentialID: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MePasskeyDeleteRsp>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.currentUserPasskeyDelete(credentialID, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Gets current user\'s passkeys
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async currentUserPasskeyGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MePasskeyRsp>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.currentUserPasskeyGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Performs session logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async currentUserSessionLogout(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.currentUserSessionLogout(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Performs session refresh
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async currentUserSessionRefresh(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthenticationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.currentUserSessionRefresh(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * Finish passkey append
         * @param {PasskeyAppendFinishReq} passkeyAppendFinishReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        currentUserPasskeyAppendFinish(passkeyAppendFinishReq: PasskeyAppendFinishReq, options?: any): AxiosPromise<void> {
            return localVarFp.currentUserPasskeyAppendFinish(passkeyAppendFinishReq, options).then((request) => request(axios, basePath));
        },
        /**
         * Start passkey append
         * @param {PasskeyAppendStartReq} passkeyAppendStartReq 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        currentUserPasskeyAppendStart(passkeyAppendStartReq: PasskeyAppendStartReq, options?: any): AxiosPromise<MePasskeyAppendStartRsp> {
            return localVarFp.currentUserPasskeyAppendStart(passkeyAppendStartReq, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete current user\'s passkeys
         * @param {string} credentialID Credential ID from passkeys
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        currentUserPasskeyDelete(credentialID: string, options?: any): AxiosPromise<MePasskeyDeleteRsp> {
            return localVarFp.currentUserPasskeyDelete(credentialID, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets current user\'s passkeys
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        currentUserPasskeyGet(options?: any): AxiosPromise<MePasskeyRsp> {
            return localVarFp.currentUserPasskeyGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Performs session logout
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        currentUserSessionLogout(options?: any): AxiosPromise<void> {
            return localVarFp.currentUserSessionLogout(options).then((request) => request(axios, basePath));
        },
        /**
         * Performs session refresh
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        currentUserSessionRefresh(options?: any): AxiosPromise<AuthenticationResponse> {
            return localVarFp.currentUserSessionRefresh(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * Finish passkey append
     * @param {PasskeyAppendFinishReq} passkeyAppendFinishReq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public currentUserPasskeyAppendFinish(passkeyAppendFinishReq: PasskeyAppendFinishReq, options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).currentUserPasskeyAppendFinish(passkeyAppendFinishReq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Start passkey append
     * @param {PasskeyAppendStartReq} passkeyAppendStartReq 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public currentUserPasskeyAppendStart(passkeyAppendStartReq: PasskeyAppendStartReq, options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).currentUserPasskeyAppendStart(passkeyAppendStartReq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete current user\'s passkeys
     * @param {string} credentialID Credential ID from passkeys
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public currentUserPasskeyDelete(credentialID: string, options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).currentUserPasskeyDelete(credentialID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets current user\'s passkeys
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public currentUserPasskeyGet(options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).currentUserPasskeyGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Performs session logout
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public currentUserSessionLogout(options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).currentUserSessionLogout(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Performs session refresh
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public currentUserSessionRefresh(options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).currentUserSessionRefresh(options).then((request) => request(this.axios, this.basePath));
    }
}



