/* tslint:disable */
/* eslint-disable */
/**
 * Corbado Frontend API
 * Overview of all Corbado Frontend API calls to implement passwordless authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@corbado.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AppleAppSiteAssociationRspApplinks } from './apple-app-site-association-rsp-applinks';
// May contain unused imports in some cases
// @ts-ignore
import { AppleAppSiteAssociationRspWebcredentials } from './apple-app-site-association-rsp-webcredentials';

/**
 * 
 * @export
 * @interface AppleAppSiteAssociationRsp
 */
export interface AppleAppSiteAssociationRsp {
    /**
     * 
     * @type {AppleAppSiteAssociationRspApplinks}
     * @memberof AppleAppSiteAssociationRsp
     */
    'applinks': AppleAppSiteAssociationRspApplinks;
    /**
     * 
     * @type {AppleAppSiteAssociationRspWebcredentials}
     * @memberof AppleAppSiteAssociationRsp
     */
    'webcredentials': AppleAppSiteAssociationRspWebcredentials;
    /**
     * 
     * @type {AppleAppSiteAssociationRspWebcredentials}
     * @memberof AppleAppSiteAssociationRsp
     */
    'appclips': AppleAppSiteAssociationRspWebcredentials;
}

