/* tslint:disable */
/* eslint-disable */
/**
 * Corbado Frontend API
 * Overview of all Corbado Frontend API calls to implement passwordless authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@corbado.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AppleAppSiteAssociationRspApplinksDetailsInner
 */
export interface AppleAppSiteAssociationRspApplinksDetailsInner {
    /**
     * 
     * @type {string}
     * @memberof AppleAppSiteAssociationRspApplinksDetailsInner
     */
    'appID': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AppleAppSiteAssociationRspApplinksDetailsInner
     */
    'paths': Array<string>;
}

