/* tslint:disable */
/* eslint-disable */
/**
 * Corbado Frontend API
 * Overview of all Corbado Frontend API calls to implement passwordless authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@corbado.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AssetLinkTarget
 */
export interface AssetLinkTarget {
    /**
     * 
     * @type {string}
     * @memberof AssetLinkTarget
     */
    'namespace': string;
    /**
     * 
     * @type {string}
     * @memberof AssetLinkTarget
     */
    'package_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetLinkTarget
     */
    'site'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AssetLinkTarget
     */
    'sha256_cert_fingerprints'?: Array<string>;
}

