/* tslint:disable */
/* eslint-disable */
/**
 * Corbado Frontend API
 * Overview of all Corbado Frontend API calls to implement passwordless authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@corbado.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AuthMethod } from './auth-method';
// May contain unused imports in some cases
// @ts-ignore
import { ShortSession } from './short-session';

/**
 * 
 * @export
 * @interface AuthenticationRsp
 */
export interface AuthenticationRsp {
    /**
     * 
     * @type {string}
     * @memberof AuthenticationRsp
     */
    'redirectURL': string;
    /**
     * Only given when using session v1
     * @type {string}
     * @memberof AuthenticationRsp
     */
    'sessionToken'?: string;
    /**
     * Only given when project environment is dev
     * @type {string}
     * @memberof AuthenticationRsp
     */
    'longSession'?: string;
    /**
     * 
     * @type {ShortSession}
     * @memberof AuthenticationRsp
     */
    'shortSession'?: ShortSession;
    /**
     * 
     * @type {Array<AuthMethod>}
     * @memberof AuthenticationRsp
     */
    'authMethods': Array<AuthMethod>;
}

