/* tslint:disable */
/* eslint-disable */
/**
 * Corbado Frontend API
 * Overview of all Corbado Frontend API calls to implement passwordless authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@corbado.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * JSON Web Key
 * @export
 * @interface Jwk
 */
export interface Jwk {
    /**
     * The specific cryptographic algorithm used with the key
     * @type {string}
     * @memberof Jwk
     */
    'alg': string;
    /**
     * The family of cryptographic algorithms used with the key
     * @type {string}
     * @memberof Jwk
     */
    'kty': string;
    /**
     * How the key was meant to be used; sig represents the signature
     * @type {string}
     * @memberof Jwk
     */
    'use': string;
    /**
     * The modulus for the RSA public key
     * @type {string}
     * @memberof Jwk
     */
    'n': string;
    /**
     * The exponent for the RSA public key
     * @type {string}
     * @memberof Jwk
     */
    'e': string;
    /**
     * The unique identifier for the key
     * @type {string}
     * @memberof Jwk
     */
    'kid': string;
}

