/* tslint:disable */
/* eslint-disable */
/**
 * Corbado Frontend API
 * Overview of all Corbado Frontend API calls to implement passwordless authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@corbado.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FullUser } from './full-user';
// May contain unused imports in some cases
// @ts-ignore
import { GenericRsp } from './generic-rsp';
// May contain unused imports in some cases
// @ts-ignore
import { RequestData } from './request-data';

/**
 * @type MeRsp
 * @export
 */
export type MeRsp = GenericRsp;


