/* tslint:disable */
/* eslint-disable */
/**
 * Corbado Frontend API
 * Overview of all Corbado Frontend API calls to implement passwordless authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@corbado.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Paging } from './paging';
// May contain unused imports in some cases
// @ts-ignore
import { PassKeyItem } from './pass-key-item';

/**
 * 
 * @export
 * @interface PassKeyList
 */
export interface PassKeyList {
    /**
     * 
     * @type {Array<PassKeyItem>}
     * @memberof PassKeyList
     */
    'passkeys': Array<PassKeyItem>;
    /**
     * 
     * @type {Paging}
     * @memberof PassKeyList
     */
    'paging'?: Paging;
}

