/* tslint:disable */
/* eslint-disable */
/**
 * Corbado Frontend API
 * Overview of all Corbado Frontend API calls to implement passwordless authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@corbado.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AuthMethod } from './auth-method';
// May contain unused imports in some cases
// @ts-ignore
import { AuthenticationRsp } from './authentication-rsp';
// May contain unused imports in some cases
// @ts-ignore
import { ShortSession } from './short-session';

/**
 * @type PassKeyLoginFinishRspAllOfData
 * @export
 */
export type PassKeyLoginFinishRspAllOfData = AuthenticationRsp;


