/* tslint:disable */
/* eslint-disable */
/**
 * Corbado Frontend API
 * Overview of all Corbado Frontend API calls to implement passwordless authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@corbado.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PassKeyItem
 */
export interface PassKeyItem {
    /**
     * 
     * @type {string}
     * @memberof PassKeyItem
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof PassKeyItem
     */
    'aaguid': string;
    /**
     * 
     * @type {string}
     * @memberof PassKeyItem
     */
    'userAgent': string;
    /**
     * 
     * @type {string}
     * @memberof PassKeyItem
     */
    'attestationType': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PassKeyItem
     */
    'transport': Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof PassKeyItem
     */
    'backupEligible': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PassKeyItem
     */
    'backupState': boolean;
    /**
     * Status
     * @type {string}
     * @memberof PassKeyItem
     */
    'status': PassKeyItemStatusEnum;
    /**
     * Timestamp of when the entity was created in yyyy-MM-dd\'T\'HH:mm:ss format
     * @type {string}
     * @memberof PassKeyItem
     */
    'created': string;
}

export const PassKeyItemStatusEnum = {
    Pending: 'pending',
    Active: 'active'
} as const;

export type PassKeyItemStatusEnum = typeof PassKeyItemStatusEnum[keyof typeof PassKeyItemStatusEnum];


