/* tslint:disable */
/* eslint-disable */
/**
 * Corbado Frontend API
 * Overview of all Corbado Frontend API calls to implement passwordless authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@corbado.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProjectConfigRspAllOfData
 */
export interface ProjectConfigRspAllOfData {
    /**
     * 
     * @type {boolean}
     * @memberof ProjectConfigRspAllOfData
     */
    'allowUserRegistration': boolean;
    /**
     * 
     * @type {string}
     * @memberof ProjectConfigRspAllOfData
     */
    'passkeyAppendInterval': string;
    /**
     * 
     * @type {string}
     * @memberof ProjectConfigRspAllOfData
     */
    'fallbackLanguage': string;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectConfigRspAllOfData
     */
    'autoDetectLanguage': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectConfigRspAllOfData
     */
    'userFullNameRequired': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectConfigRspAllOfData
     */
    'webComponentDebug': boolean;
    /**
     * 
     * @type {string}
     * @memberof ProjectConfigRspAllOfData
     */
    'environment': string;
}

