/* tslint:disable */
/* eslint-disable */
/**
 * Corbado Frontend API
 * Overview of all Corbado Frontend API calls to implement passwordless authentication.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@corbado.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ShortSession
 */
export interface ShortSession {
    /**
     * 
     * @type {string}
     * @memberof ShortSession
     */
    'key': string;
    /**
     * 
     * @type {string}
     * @memberof ShortSession
     */
    'value': string;
    /**
     * 
     * @type {string}
     * @memberof ShortSession
     */
    'domain': string;
    /**
     * 
     * @type {string}
     * @memberof ShortSession
     */
    'path': string;
    /**
     * 
     * @type {boolean}
     * @memberof ShortSession
     */
    'secure': boolean;
    /**
     * 
     * @type {string}
     * @memberof ShortSession
     */
    'expires': string;
    /**
     * 
     * @type {string}
     * @memberof ShortSession
     */
    'sameSite': string;
}

