# When running this on a different self-hosted runner, the following needs
# to be done before the workflow will properly run:
#   1. Install Node.js and npm on the server
#   2. Change the PLAYWRIGHT_NUM_CORES value in the bottom of this file to
#      match the number of cores on the server

name: End-to-End testing check for Playground Apps
env:
  BRANCH_NAME_RAW: ${{ github.head_ref || github.ref_name }}

on:
  pull_request:
  push:
    branches:
      # - main
      # - develop

jobs:
  prepare:
    runs-on: [ self-hosted, "javascript" ]
    outputs:
      BRANCH_NAME: ${{ steps.set_branch_name.outputs.BRANCH_NAME }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Normalize branch name
      id: set_branch_name
      run: echo "BRANCH_NAME=$(echo $BRANCH_NAME_RAW | tr '/_' '-')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set up Node.js
      uses: actions/setup-node@v4

    # # The self-hosted runners are so fast that caching overhead is more
    # # expensive than just installing the dependencies
    # - name: Cache dependencies
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.npm
    #     key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
    #     restore-keys: ${{ runner.os }}-build-

    - name: Install Dependencies
      run: |
        npm ci
        npm install lerna

    # Compressing node_modules preserves file permissions and decreases download/upload times
    - name: 'Tar node_modules'
      run: tar -czf node_modules.tar.gz node_modules

    - name: Upload node_modules
      uses: actions/upload-artifact@v4
      with:
        name: node-modules
        path: node_modules.tar.gz

  e2e-tests:
    timeout-minutes: 60
    needs: prepare
    runs-on: [ self-hosted, "Deploy" ]
    strategy:
      matrix:
        include:
          - app: "react"
            url: ".react.playground.corbado.io/"
            type: "ui"
          # - app: "react-sdk"
          #   url: ".react-sdk.korbado.com/"
          #   type: "sdk"
          # Add more playground apps as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
          path: .

      - name: Extract node_modules
        run: tar -xzf node_modules.tar.gz

      - name: Install Playwright Browsers
        run: |
          npx playwright install --with-deps
          npx playwright install msedge

      - name: Run E2E Test for ${{ matrix.app }}
        run: |
          if [ "${{ matrix.type }}" = "sdk" ]; then
            npm run test:e2e:sdk
          else
            npm run test:e2e:ui
          fi
        env:
          PLAYWRIGHT_NUM_CORES: 8
          PLAYWRIGHT_TEST_URL: ${{ format('https://{0}{1}', needs.prepare.outputs.BRANCH_NAME, matrix.url) }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: packages/tests-e2e/playwright-report/
          retention-days: 30
