name: Commitly End-to-End testing check for Playground Apps
env:
  BRANCH_NAME_RAW: ${{ github.head_ref || github.ref_name }}

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Normalize branch name
        run: |
          echo "BRANCH_NAME=$(echo $BRANCH_NAME_RAW | tr '/_' '-')" >> "$GITHUB_ENV"
        shell: bash

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: |
          npm ci
          npm install lerna

      - name: Install Playwright Browsers
        run: |
          npx playwright install --with-deps

      - name: Run E2E Test for react
        run: |
          BRANCH_NAME=$(echo $BRANCH_NAME_RAW | tr '/_' '-')
          export PLAYWRIGHT_TEST_URL="https://$BRANCH_NAME.react.playground.corbado.io"
          PLAYWRIGHT_TEST_URL=$PLAYWRIGHT_TEST_URL npm run test:e2e:ui:commitly
        env:
          PLAYWRIGHT_NUM_CORES: 2
          PLAYWRIGHT_JWT_TOKEN: ${{ secrets.PLAYWRIGHT_JWT_TOKEN }}
          PLAYWRIGHT_MICROSOFT_EMAIL: ${{ secrets.PLAYWRIGHT_MICROSOFT_EMAIL }}
          PLAYWRIGHT_MICROSOFT_PASSWORD: ${{ secrets.PLAYWRIGHT_MICROSOFT_PASSWORD }}
          GITHUB_RUN_ID: ${{ github.run_id }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: packages/tests-e2e/playwright-report/
          retention-days: 30
